CUDA_VISIBLE_DEVICES=0 python3 finetune.py\
    --train_table_text_path ../data/tiny_data/tiny_table.txt\
    --train_content_text_path ../data/tiny_data/tiny_content_plan.txt\
    --train_reference_sentence_path ../data/tiny_data/tiny_reference.txt\
    --train_processed_file_path ../data/tiny_data/tiny_processed_totto_dev.jsonl\
    --dev_table_text_path ../data/tiny_data/tiny_table.txt\
    --dev_content_text_path ../data/tiny_data/tiny_content_plan.txt\
    --dev_reference_sentence_path ../data/tiny_data/tiny_reference.txt\
    --dev_processed_file_path ../data/tiny_data/tiny_processed_totto_dev.jsonl\
    --dev_reference_path ../data/tiny_data/tiny_raw_totto_dev.jsonl\
    --special_token_path ../data/totto_col_header_vocab.txt\
    --total_steps 10\
    --print_every 1\
    --eval_every 4\
    --pretrained_ckpt_path ./ckpt/pretrain/generator-pretrain.ckpt\
    --ckpt_path ./test_ckpt/finetune/\